# Generated by Django 3.2.7 on 2021-10-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='item',
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listings'),
        ),
    ]
