# Generated by Django 3.2.7 on 2021-10-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211006_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listings'),
        ),
    ]
