# Generated by Django 3.2.7 on 2021-10-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211006_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
