# Generated by Django 3.2.7 on 2021-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20211009_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='ini_bid',
            field=models.IntegerField(),
        ),
    ]
