# Generated by Django 3.2.7 on 2021-10-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listings_ini_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
