# Generated by Django 3.2.7 on 2021-10-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='item',
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
    ]
